apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: toggle-master
  labels:
    app: flag-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
      - name: flag-service
        image: 581571885952.dkr.ecr.us-east-1.amazonaws.com/toggle-master/flag-service:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        
        envFrom:
        - configMapRef:
            name: flag-service-config
        
        env:
        - name: DATABASE_URL
          value: "postgres://flag_user:flag_password@flag-db.cahgwak00ah1.us-east-1.rds.amazonaws.com:5432/flags_db"
        - name:  AUTH_SERVICE_URL 
          value: "http://auth-service:8001"
        - name: PORT
          value: "8002"

        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 2
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
