apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: toggle-master
type: Opaque
data:
  # base64: auth_password
  postgres-password: YXV0aF9wYXNzd29yZA==
  # base64: admin-secreto-123
  master-key: YWRtaW4tc2VjcmV0by0xMjM=
