apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: toggle-master
type: Opaque
data:
  # base64: 123456678
  postgres-password: MTIzNDU2Njc4
  # base64: admin-secreto-123
  master-key: YWRtaW4tc2VjcmV0by0xMjM=
  # base64: postgres://teste:123456678@dev-auth-service-database.cahgwak00ah1.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require
  database-url: cG9zdGdyZXM6Ly90ZXN0ZToxMjM0NTY2NzhAZGV2LWF1dGgtc2VydmljZS1kYXRhYmFzZS5jYWhnd2FrMDBhaDEudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvYXV0aF9kYj9zc2xtb2RlPXJlcXVpcmU=
