apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: toggle-master
type: Opaque
data:
  # base64: auth_password
  postgres-password: YXV0aF9wYXNzd29yZA==
  # base64: admin-secreto-123
  master-key: YWRtaW4tc2VjcmV0by0xMjM=
  # base64: postgres://auth_user:auth_password@auth-db.cahgwak00ah1.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require
  database-url: cG9zdGdyZXM6Ly9hdXRoX3VzZXI6YXV0aF9wYXNzd29yZEBhdXRoLWRiLmNhaGd3YWswMGFoMS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9hdXRoX2RiP3NzbG1vZGU9cmVxdWlyZQ==
